import popularProducts from "../assets/images/PopularProducts";

// Dummy Data
export const ProductsData = [
  {
    id: 1,
    image: popularProducts.image1,
    title: "True Balance Vitamin",
    rating: 4.5,
    price: "₹250.0",
    originalPrice: "₹300.0",
    badge: "Hot",
    badgeColor: "bg-orange-500",
    description: "True Balance Vitamin helps to maintain overall health and well-being. It provides essential vitamins and minerals that support various bodily functions. This supplement is designed to fill nutritional gaps in your diet and ensure you get the necessary nutrients for optimal health. It is especially beneficial for those with a busy lifestyle who may not always eat a balanced diet.",
    shortDescription: "Essential vitamins for overall health.",
    stock: "Available",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 1"],
  },
  {
    id: 2,
    image: popularProducts.image2,
    title: "Body Lotion 200ml",
    rating: 4,
    price: "₹150.0",
    originalPrice: "₹200.0",
    badge: "New",
    badgeColor: "bg-green-500",
    description: "This Body Lotion provides deep hydration and nourishment to your skin. It is enriched with natural ingredients like shea butter and aloe vera that leave your skin feeling soft and smooth. The non-greasy formula absorbs quickly, making it perfect for daily use. It helps to restore the skin's natural moisture barrier and protects against dryness.",
    shortDescription: "Deep hydration and nourishment.",
    stock: "Available",
    categories: ["Skin Care", "Body Care"],
    brands: ["Brand 2"],
  },
  {
    id: 3,
    image: popularProducts.image3,
    title: "Face Mask",
    rating: 4.5,
    price: "₹50.0",
    originalPrice: "₹70.0",
    badge: "Trending",
    badgeColor: "bg-[#579f97]",
    description: "This Face Mask helps to cleanse and rejuvenate your skin. It removes impurities and excess oil, leaving your skin feeling fresh and revitalized. The mask contains natural ingredients like clay and charcoal that draw out toxins and unclog pores. Regular use can help to improve skin texture and reduce the appearance of blemishes.",
    shortDescription: "Cleanses and rejuvenates skin.",
    stock: "Available",
    categories: ["Skin Care", "Face Care"],
    brands: ["Brand 3"],
  },
  {
    id: 4,
    image: popularProducts.image4,
    title: "Vitamin B12",
    rating: 4.5,
    price: "₹2000.0",
    originalPrice: "₹2500.0",
    badge: "Out of Stock",
    badgeColor: "bg-red-500",
    description: "Vitamin B12 is essential for maintaining healthy nerve cells and producing DNA. It also helps to prevent megaloblastic anemia, a condition that makes people tired and weak. This supplement is particularly important for vegetarians and vegans, as B12 is primarily found in animal products. It supports energy production and cognitive function.",
    shortDescription: "Essential for nerve health and DNA production.",
    stock: "Out of Stock",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 1"],
  },
  {
    id: 5,
    image: popularProducts.image5,
    title: "Vitamin C",
    rating: 3,
    price: "₹250.0",
    originalPrice: "₹300.0",
    badge: "10% OFF",
    badgeColor: "bg-orange-500",
    description: "Vitamin C is a powerful antioxidant that helps to protect your cells from damage. It also supports a healthy immune system and promotes skin health. This supplement can help to reduce the duration of colds and improve skin elasticity. It is essential for the production of collagen, which is important for the health of your skin, hair, and nails.",
    shortDescription: "Powerful antioxidant for immune support.",
    stock: "Available",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 2"],
  },
  {
    id: 6,
    image: popularProducts.image6,
    title: "Vitamin D3",
    rating: 4.5,
    price: "₹250.0",
    originalPrice: "₹300.0",
    badge: "10% OFF",
    badgeColor: "bg-orange-500",
    description: "Vitamin D3 helps to maintain healthy bones and teeth. It also supports your immune system, brain, and nervous system. This supplement is particularly important for individuals who do not get enough sunlight exposure. It aids in the absorption of calcium and phosphorus, which are critical for bone health.",
    shortDescription: "Supports bone health and immune system.",
    stock: "Available",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 4"],
  },
  {
    id: 7,
    image: popularProducts.image5,
    title: "Vitamin C",
    rating: 3,
    price: "₹250.0",
    originalPrice: "₹300.0",
    badge: "10% OFF",
    badgeColor: "bg-orange-500",
    description: "Vitamin C is a powerful antioxidant that helps to protect your cells from damage. It also supports a healthy immune system and promotes skin health. This supplement can help to reduce the duration of colds and improve skin elasticity. It is essential for the production of collagen, which is important for the health of your skin, hair, and nails.",
    shortDescription: "Powerful antioxidant for immune support.",
    stock: "Available",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 2"],
  },
  {
    id: 8,
    image: popularProducts.image4,
    title: "Vitamin B12",
    rating: 4.5,
    price: "₹2000.0",
    originalPrice: "₹2500.0",
    badge: "New",
    badgeColor: "bg-orange-500",
    description: "Vitamin B12 is essential for maintaining healthy nerve cells and producing DNA. It also helps to prevent megaloblastic anemia, a condition that makes people tired and weak. This supplement is particularly important for vegetarians and vegans, as B12 is primarily found in animal products. It supports energy production and cognitive function.",
    shortDescription: "Essential for nerve health and DNA production.",
    stock: "Available",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 1"],
  },
  {
    id: 9,
    image: popularProducts.image1,
    title: "True Balance Vitamin",
    rating: 4.5,
    price: "₹250.0",
    originalPrice: "₹300.0",
    badge: "Out of Stock",
    badgeColor: "bg-red-500",
    description: "True Balance Vitamin helps to maintain overall health and well-being. It provides essential vitamins and minerals that support various bodily functions. This supplement is designed to fill nutritional gaps in your diet and ensure you get the necessary nutrients for optimal health. It is especially beneficial for those with a busy lifestyle who may not always eat a balanced diet.",
    shortDescription: "Essential vitamins for overall health.",
    stock: "Out of Stock",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 5"],
  },
  {
    id: 10,
    image: popularProducts.image2,
    title: "Body Lotion 200ml",
    rating: 4,
    price: "₹150.0",
    originalPrice: "₹200.0",
    badge: "" || null,
    badgeColor: "",
    description: "This Body Lotion provides deep hydration and nourishment to your skin. It is enriched with natural ingredients like shea butter and aloe vera that leave your skin feeling soft and smooth. The non-greasy formula absorbs quickly, making it perfect for daily use. It helps to restore the skin's natural moisture barrier and protects against dryness.",
    shortDescription: "Deep hydration and nourishment.",
    stock: "Available",
    categories: ["Skin Care", "Body Care"],
    brands: ["Brand 6"],
  },
];
