import popularProducts from "../assets/images/PopularProducts";

// Dummy Data
export const ProductsData = [
  {
    id: 1,
    image: popularProducts.image1,
    title: "True Balance Vitamin",
    rating: 4.5,
    price: "₹250.0",
    badge: "Hot",
    badgeColor: "bg-orange-500",
    discription: "This is a dummy discription",
    stock: "Avail",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 1"],
  },
  {
    id: 2,
    image: popularProducts.image2,
    title: "Body Lotion 200ml",
    rating: 4,
    price: "₹150.0",
    badge: "New",
    badgeColor: "bg-green-500",
    categories: ["Skin Care", "Body Care"],
    brands: ["Brand 2"],
  },
  {
    id: 3,
    image: popularProducts.image3,
    title: "Face Mask",
    rating: 4.5,
    price: "₹50.0",
    badge: "Trending",
    badgeColor: "bg-[#579f97]",
    categories: ["Skin Care", "Face Care"],
    brands: ["Brand 3"],
  },
  { 
    id: 4,
    image: popularProducts.image4,
    title: "Vitamin B12",
    rating: 4.5,
    price: "₹2000.0",
    badge: "Out of Stock",
    badgeColor: "bg-red-500",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 1"],
  },
  {
    id: 5,
    image: popularProducts.image5,
    title: "Vitamin C",
    rating: 3,
    price: "₹250.0",
    badge: "10% OFF",
    badgeColor: "bg-orange-500",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 2"],
  },
  {
    id: 6,
    image: popularProducts.image6,
    title: "Vitamin D3",
    rating: 4.5,
    price: "₹250.0",
    badge: "10% OFF",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 4"],
  },
  {
    id: 7,
    image: popularProducts.image5,
    title: "Vitamin C",
    rating: 3,
    price: "₹250.0",
    badge: "10% OFF",
    badgeColor: "bg-orange-500",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 2"],
  },
  {
    id: 8,
    image: popularProducts.image4,
    title: "Vitamin B12",
    rating: 4.5,
    price: "₹2000.0",
    badge: "New",
    badgeColor: "bg-orange-500",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 1"],
  },
  {
    id: 9,
    image: popularProducts.image1,
    title: "True Balance Vitamin",
    rating: 4.5,
    price: "₹250.0",
    badge: "Out of Stock",
    badgeColor: "bg-red-500",
    categories: ["Vitamins", "Supplements"],
    brands: ["Brand 5"],
  },
  {
    id: 10,
    image: popularProducts.image2,
    title: "Body Lotion 200ml",
    rating: 4,
    price: "₹150.0",
    badge: "" || null,
    badgeColor: "",
    categories: ["Skin Care", "Body Care"],
    brands: ["Brand 6"],
  },
];
